# Generated by Django 3.1 on 2020-09-30 16:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cattype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Circl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheading', models.CharField(max_length=50)),
                ('cdesc', models.CharField(max_length=500)),
                ('che', models.CharField(blank=True, max_length=50, null=True)),
                ('cdesc2', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheadng', models.CharField(max_length=40)),
                ('cdes', models.CharField(max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name='Homedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1_desc', models.CharField(max_length=800)),
                ('h2_brief', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Offerproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oimg', models.ImageField(blank=True, null=True, upload_to='')),
                ('oproname', models.CharField(max_length=40)),
                ('oprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=30)),
                ('categoryy', models.CharField(blank=True, default=1, max_length=20)),
                ('desc', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('discountdesc', models.CharField(blank=True, max_length=50)),
                ('oldprice', models.CharField(blank=True, max_length=10)),
                ('newdiscount', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('protype', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sliderhome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheadng', models.CharField(max_length=30)),
                ('sdesc', models.CharField(max_length=255)),
                ('simg', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tabt', models.CharField(max_length=100)),
                ('tname', models.CharField(max_length=20)),
                ('timg', models.ImageField(blank=True, null=True, upload_to='')),
                ('tdesc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headng', models.CharField(max_length=30)),
                ('headng2', models.CharField(max_length=30)),
                ('workdesc', models.CharField(max_length=255)),
                ('workdesc2', models.CharField(max_length=255)),
                ('wimg', models.ImageField(blank=True, null=True, upload_to='')),
                ('wimg2', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=30)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmeryyapp.category1')),
            ],
        ),
        migrations.CreateModel(
            name='Productview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trialdays', models.CharField(max_length=255)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmeryyapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proname', models.CharField(max_length=30)),
                ('pric', models.IntegerField()),
                ('quant', models.IntegerField()),
                ('farmer_name', models.CharField(blank=True, max_length=30)),
                ('orchard', models.CharField(blank=True, max_length=40)),
                ('expted_delivery', models.DateField()),
                ('pre_delivery', models.DateField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmeryyapp.category1')),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmeryyapp.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('phno', models.CharField(max_length=12)),
                ('refphno', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.CharField(max_length=255)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmeryyapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product_id')},
                'index_together': {('user', 'product_id')},
            },
        ),
    ]
