# Generated by Django 3.0.3 on 2020-08-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmeryyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='newdiscount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='oldprice',
            field=models.IntegerField(null=True),
        ),
    ]
