# Generated by Django 3.0.3 on 2020-08-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmeryyapp', '0002_auto_20200809_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='newdiscount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='oldprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
