# Generated by Django 3.0.3 on 2020-08-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmeryyapp', '0003_auto_20200809_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='newdiscount',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='oldprice',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
    ]
