# Generated by Django 3.0.3 on 2020-08-08 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmeryyapp', '0004_auto_20200809_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cattype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('protype', models.CharField(max_length=30)),
                ('category1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmeryyapp.Category1')),
            ],
        ),
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proname', models.CharField(max_length=30)),
                ('pric', models.IntegerField()),
                ('quant', models.IntegerField()),
                ('farmer_name', models.CharField(blank=True, max_length=30)),
                ('orchard', models.CharField(blank=True, max_length=40)),
                ('expted_delivery', models.DateField(auto_now=True)),
                ('pre_delivery', models.DateField(auto_now=True)),
                ('category1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmeryyapp.Category1')),
                ('producttype_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='farmeryyapp.ProductType')),
            ],
        ),
    ]
