# Generated by Django 3.0.3 on 2020-08-08 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmeryyapp', '0005_category1_product2_producttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='category1_id',
        ),
    ]
