# Generated by Django 3.0.3 on 2020-08-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmeryyapp', '0006_remove_producttype_category1_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product2',
            name='proimg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
