# Generated by Django 3.1 on 2020-09-01 09:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmeryyapp', '0007_product2_proimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=20)),
                ('timg', models.ImageField(blank=True, null=True, upload_to='')),
                ('tdesc', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product2',
            name='producttype_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product2',
            name='expted_delivery',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product2',
            name='pre_delivery',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=30)),
                ('category1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmeryyapp.category1')),
            ],
        ),
        migrations.CreateModel(
            name='Productview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trialdays', models.CharField(max_length=255)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmeryyapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='product2',
            name='subcategroy_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmeryyapp.subcategory'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.CharField(max_length=255)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmeryyapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product_id')},
                'index_together': {('user', 'product_id')},
            },
        ),
    ]
