# Generated by Django 3.0.3 on 2020-08-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmeryyapp', '0008_auto_20200809_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=20)),
                ('timg', models.ImageField(blank=True, null=True, upload_to='')),
                ('tdesc', models.CharField(max_length=100)),
            ],
        ),
    ]
