# Generated by Django 3.1 on 2020-08-24 18:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmeryyapp', '0010_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='product_rat',
            new_name='product_id',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'product_id')},
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together={('user', 'product_id')},
        ),
    ]
